(function(g){var window=this;var Qwa=function(a,b){return g.Lb(a,b)},Y5=function(a,b,c){a.A.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.fn(a.A,b,c)},Rwa=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.fo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.eo(e)&&c.push(d)},a);
return c},Swa=function(a,b){var c=Rwa(a,b);
(0,g.x)(c,function(d){g.fo.prototype.remove.call(this,d)},a)},Twa=function(a){if(a.Vc){if(a.Vc.locationOverrideToken)return{locationOverrideToken:a.Vc.locationOverrideToken};
if(null!=a.Vc.latitudeE7&&null!=a.Vc.longitudeE7)return{latitudeE7:a.Vc.latitudeE7,longitudeE7:a.Vc.longitudeE7}}return null},Uwa=function(a,b){g.cb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Vwa=function(a,b){var c=b instanceof g.yc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},b6=function(){},Wwa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Xwa=function(a){if(a.Id&&"function"==typeof a.Id)return a.Id();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Hb(a)},Ywa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)(0,g.x)(a,b,void 0);else{if(a.ue&&"function"==typeof a.ue)var c=a.ue();else if(a.Id&&"function"==typeof a.Id)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Ib(a);d=Xwa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Zwa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Ro[a]=!0;
var c=g.Po();c&&c.publish.apply(c,arguments);g.Ro[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Rm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$wa(this,a.capabilities||""),axa(this,a.experiments||""))},$wa=function(a,b){a.capabilities.clear();
(0,g.ze)(b.split(","),g.Qa(Qwa,bxa)).forEach(function(c){a.capabilities.add(c)})},axa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},cxa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},dxa=function(a){return new e6(a)},exa=function(a){return Array.isArray(a)?(0,g.Hc)(a,dxa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return Array.isArray(a)?"["+(0,g.Hc)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},fxa=function(a){return(0,g.Hc)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Za(a,function(c){return f6(c,b)})},gxa=function(){var a=(0,g.us)();
a&&Swa(a,a.o.dg(!0))},l6=function(){var a=g.xs("yt-remote-connected-devices")||[];
g.tb(a);return a},hxa=function(a){if(g.db(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Hc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},ixa=function(a){g.ws("yt-remote-connected-devices",a,86400)},n6=function(){if(m6)return m6;
var a=g.xs("yt-remote-device-id");a||(a=i6(),g.ws("yt-remote-device-id",a,31536E3));for(var b=l6(),c=1,d=a;g.cb(b,d);)c++,d=a+"#"+c;return m6=d},o6=function(){var a=l6(),b=n6();
g.cb(a,b);g.zs()&&g.wb(a,b);a=hxa(a);if(g.db(a))try{g.Gq("remote_sid")}catch(c){}else try{g.Eq("remote_sid",a.join(","),-1)}catch(c){}},jxa=function(){return g.xs("yt-remote-session-browser-channel")},kxa=function(){return g.xs("yt-remote-local-screens")||[]},lxa=function(){g.ws("yt-remote-lounge-token-expiration",!0,86400)},mxa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Hc)(kxa(),function(d){return d.loungeToken}),c=(0,g.Hc)(a,function(d){return d.loungeToken});
(0,g.yi)(c,function(d){return!g.cb(b,d)})&&lxa();
g.ws("yt-remote-local-screens",a,31536E3)},nxa=function(a,b){g.ws("yt-remote-session-browser-channel",a);
g.ws("yt-remote-session-screen-id",b);var c=l6(),d=n6();g.cb(c,d)||c.push(d);ixa(c);o6()},p6=function(a){a||(g.ys("yt-remote-session-screen-id"),g.ys("yt-remote-session-video-id"));
o6();a=l6();g.gb(a,n6());ixa(a)},oxa=function(){if(!q6){var a=g.po();
a&&(q6=new g.Zn(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},pxa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},qxa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r6=function(a){a.length?rxa(a.shift(),function(){r6(a)}):s6()},sxa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},rxa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},s6=function(){var a=qxa();
a&&a(!1,"No cast extension found")},uxa=function(){if(txa){var a=2,b=qxa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;rxa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s6,c)}},vxa=function(){uxa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);r6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},t6=function(a,b,c){g.z.call(this);
this.D=null!=c?(0,g.w)(a,c):a;this.Cd=b;this.C=(0,g.w)(this.qF,this);this.o=!1;this.u=0;this.A=this.Ja=null;this.B=[]},u6=function(a,b,c){g.z.call(this);
this.B=null!=c?a.bind(c):a;this.Cd=b;this.A=null;this.o=!1;this.u=0;this.Ja=null},v6=function(a){a.Ja=g.Yf(function(){a.Ja=null;
a.o&&!a.u&&(a.o=!1,v6(a))},a.Cd);
var b=a.A;a.A=null;a.B.apply(null,b)},w6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Wwa(a)},x6=function(){},y6=function(){},wxa=function(){},yxa=function(a){return(a=xxa(a))?new ActiveXObject(a):new XMLHttpRequest},xxa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},z6=function(a,b,c,d){this.o=a;
this.A=b;this.H=c;this.G=d||1;this.C=45E3;this.B=new g.x1(this);this.u=new g.Xf;this.u.setInterval(250)},Axa=function(a,b,c){a.Nj=1;
a.Yg=Z5(b.clone());a.hj=c;a.D=!0;zxa(a,null)},A6=function(a,b,c,d,e){a.Nj=1;
a.Yg=Z5(b.clone());a.hj=null;a.D=c;e&&(a.eC=!1);zxa(a,d)},zxa=function(a,b){a.Jk=(0,g.C)();
B6(a);a.Vh=a.Yg.clone();$5(a.Vh,"t",a.G);a.Ym=0;a.Nc=a.o.yr(a.o.Nm()?b:null);0<a.us&&(a.Qp=new u6((0,g.w)(a.bD,a,a.Nc),a.us));a.B.na(a.Nc,"readystatechange",a.XN);var c=a.Fi?g.Rb(a.Fi):{};a.hj?(a.Aq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Vh,a.Aq,a.hj,c)):(a.Aq="GET",a.eC&&!g.oe&&(c.Connection="close"),a.Nc.send(a.Vh,a.Aq,null,c));a.o.gf(1)},Dxa=function(a,b,c){for(var d=!0;!a.ni&&a.Ym<c.length;){var e=Bxa(a,c);
if(e==C6){4==b&&(a.qh=4,D6(15),d=!1);break}else if(e==Cxa){a.qh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.qh=1,D6(17),d=!1);a.kf=a.kf&&d;d||(F6(a),G6(a))},Bxa=function(a,b){var c=a.Ym,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return Cxa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Ym=d+c;return e},Fxa=function(a,b){a.Jk=(0,g.C)();
B6(a);var c=b?window.location.hostname:"";a.Vh=a.Yg.clone();Y5(a.Vh,"DOMAIN",c);Y5(a.Vh,"t",a.G);try{a.qf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.qh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in Exa)k=H6[l]=Exa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.$c(g.bc("b/12014412"),d+"</body></html>");a.qf.open();a.qf.write(g.Vc(c));a.qf.close();a.qf.parentWindow.m=(0,g.w)(a.tN,a);a.qf.parentWindow.d=(0,g.w)(a.mB,a,!0);a.qf.parentWindow.rpcClose=(0,g.w)(a.mB,a,!1);c=a.qf.createElement("DIV");a.qf.parentWindow.document.body.appendChild(c);d=g.Bc(a.Vh.toString());d=g.hd(g.zc(d));d=g.$c(g.bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ad(c,d);a.o.gf(1)},B6=function(a){a.tv=(0,g.C)()+a.C;
Gxa(a,a.C)},Gxa=function(a,b){if(null!=a.Vk)throw Error("WatchDog timer not null");
a.Vk=I6((0,g.w)(a.BN,a),b)},J6=function(a){a.Vk&&(g.v.clearTimeout(a.Vk),a.Vk=null)},G6=function(a){a.o.Tx()||a.ni||a.o.po(a)},F6=function(a){J6(a);
g.Le(a.Qp);a.Qp=null;a.u.stop();g.Bra(a.B);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.qf&&(a.qf=null)},E6=function(a,b){try{a.o.eB(a,b),a.o.gf(4)}catch(c){}},Ixa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Hxa(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Ixa(a,b,c,d,f)},f)})}},Hxa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Vwa(d,a)},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Jxa=function(a){this.o=a;
this.u=new x6},Kxa=function(a){var b=L6(a.o,a.kl,"/mail/images/cleardot.gif");
Z5(b);Ixa(b.toString(),5E3,(0,g.w)(a.pE,a),3,2E3);a.gf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Ud=new z6(a,void 0,void 0,void 0),a.Ud.Fi=a.rs,b=a.o,b=L6(b,b.Nm()?a.Jl:null,a.ts),D6(5),!g.me||g.Qd(10))$5(b,"TYPE","xmlhttp"),A6(a.Ud,b,!1,a.Jl,!1);else{$5(b,"TYPE","html");var c=a.Ud;a=!!a.Jl;c.Nj=3;c.Yg=Z5(b.clone());Fxa(c,a)}},O6=function(a){g.lf.call(this);
this.headers=new g.Rm;this.V=a||null;this.A=!1;this.S=this.o=null;this.ga=this.J="";this.D=0;this.B="";this.C=this.aa=this.H=this.W=!1;this.G=0;this.R=null;this.ea="";this.N=this.ba=!1},Lxa=function(a){return g.me&&g.Pd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Mxa=function(a){return"content-type"==a.toLowerCase()},Oxa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.D=5;Nxa(a);P6(a)},Nxa=function(a){a.W||(a.W=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Qxa=function(a){if(a.A&&"undefined"!=typeof g.C1)if(a.S[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.H&&4==Q6(a))g.Yf(a.aB,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.rd(1,String(a.J));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Pxa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.D=6;try{var l=2<Q6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";Nxa(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){Rxa(a);
var c=a.o,d=a.S[0]?g.Ia:null;a.o=null;a.S=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Rxa=function(a){a.o&&a.N&&(a.o.ontimeout=null);
a.R&&(g.v.clearTimeout(a.R),a.R=null)},Q6=function(a){return a.o?a.o.readyState:0},S6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.ga+" "+a.J+" "+a.getStatus()+"]"},T6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new x6;this.H=a||null;this.J=null!=b?b:null;this.D=c||!1},Sxa=function(a,b){this.o=a;
this.map=b;this.context=null},Txa=function(a){g.Ne.call(this,"statevent",a)},Uxa=function(a,b){g.Ne.call(this,"timingevent",a);
this.size=b},Vxa=function(a){g.Ne.call(this,"serverreachability",a)},Yxa=function(a){Wxa(a);
if(3==a.o){var b=a.rm++,c=a.Yn.clone();Y5(c,"SID",a.A);Y5(c,"RID",b);Y5(c,"TYPE","terminate");U6(a,c);b=new z6(a,a.A,b,void 0);b.Nj=2;b.Yg=Z5(c.clone());Vwa(new Image,b.Yg.toString());b.Jk=(0,g.C)();B6(b)}Xxa(a)},Zxa=function(a){a.ME(1,0);
a.Yn=L6(a,null,a.qs);V6(a)},Wxa=function(a){a.bh&&(a.bh.abort(),a.bh=null);
a.jc&&(a.jc.cancel(),a.jc=null);a.eg&&(g.v.clearTimeout(a.eg),a.eg=null);W6(a);a.Od&&(a.Od.cancel(),a.Od=null);a.ih&&(g.v.clearTimeout(a.ih),a.ih=null)},$xa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Sxa(a.SJ++,b));2!=a.o&&3!=a.o||V6(a)},V6=function(a){a.Od||a.ih||(a.ih=I6((0,g.w)(a.lB,a),0),a.Gj=0)},bya=function(a,b){if(1==a.o){if(!b){a.rm=Math.floor(1E5*Math.random());
var c=a.rm++,d=new z6(a,"",c,void 0);d.Fi=null;var e=X6(a),f=a.Yn.clone();Y5(f,"RID",c);Y5(f,"CVER","1");U6(a,f);Axa(d,f,e);a.Od=d;a.o=2}}else 3==a.o&&(b?aya(a,b):0==a.u.length||a.Od||aya(a))},aya=function(a,b){if(b)if(6<a.oi){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.rm-1;var d=X6(a)}else c=b.H,d=b.hj;else c=a.rm++,d=X6(a);var e=a.Yn.clone();Y5(e,"SID",a.A);Y5(e,"RID",c);Y5(e,"AID",a.ak);U6(a,e);c=new z6(a,a.A,c,a.Gj+1);c.Fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Od=c;Axa(c,e,d)},U6=function(a,b){if(a.yd){var c=a.yd.rx();
c&&g.Bb(c,function(d,e){Y5(b,e,d)})}},X6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.oi&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.oi?e:f-d;try{g.Bb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},cya=function(a){a.jc||a.eg||(a.G=1,a.eg=I6((0,g.w)(a.kB,a),0),a.wj=0)},Y6=function(a){if(a.jc||a.eg||3<=a.wj)return!1;
a.G++;a.eg=I6((0,g.w)(a.kB,a),dya(a,a.wj));a.wj++;return!0},M6=function(a,b,c){a.yq=c;
a.zf=b.wg;a.D||Zxa(a)},W6=function(a){null!=a.wi&&(g.v.clearTimeout(a.wi),a.wi=null)},dya=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.yd&&(c=null);var d=(0,g.w)(a.HO,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),Z5(c));Hxa(c.toString(),1E4,d)}else D6(2);eya(a,b)},eya=function(a,b){a.o=0;
a.yd&&a.yd.Fw(b);Xxa(a);Wxa(a)},Xxa=function(a){a.o=0;
a.zf=-1;if(a.yd)if(0==a.B.length&&0==a.u.length)a.yd.mr();else{g.kb(a.B);var b=g.kb(a.u);a.B.length=0;a.u.length=0;a.yd.mr(b)}},L6=function(a,b,c){var d=g.bn(c);
if(""!=d.o)b&&g.Wm(d,b+"."+d.o),g.Xm(d,d.B);else{var e=window.location;d=Zwa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Al&&g.Bb(a.Al,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.oi);U6(a,d);return d},I6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){$6.dispatchEvent(new Txa($6,a))},fya=function(){},gya=function(){this.o=[];
this.u=[]},hya=function(a,b){this.action=a;
this.params=b||{}},a7=function(a,b){g.z.call(this);
this.o=new g.H(this.mN,0,this);g.A(this,this.o);this.Cd=5E3;this.u=0;if(g.Ma(a))b&&(a=(0,g.w)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.w)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},b7=function(a,b,c){this.R=a;
this.D=b;this.A=new g.Yn;this.u=new a7(this.kO,this);this.o=null;this.Fb=!1;this.C=null;this.J="";this.H=this.B=0;this.G=[];this.N=c||!1},iya=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.yq,sessionId:a.o.A,arrayId:a.o.ak}},jya=function(a,b){a.H=b||0;
a.u.stop();a.o&&(3==a.o.o&&bya(a.o),Yxa(a.o));a.H=0},c7=function(a){return!!a.o&&3==a.o.o},kya=function(a,b){(a.D.loungeIdToken=b)||a.u.stop()},d7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.rd(4,a))||"";b&&(this.port=":"+b);this.domain=g.sd(a)||"";a=g.Nc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.vc(a,"10.0")&&(this.u=!1))},e7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Cd(c+b,{})},f7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.A,e),ne:g.Qa(a.C,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xq(b,a)},oya=function(){var a=lya;
mya();g7.push(a);nya(g7)},h7=function(a,b){mya();
var c=g7,d=pya(a,String(b));g.db(c)?qya(d):(nya(c),(0,g.x)(c,function(e){e(d)}))},mya=function(){g7||(g7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",g7,void 0))},qya=function(a){var b=(i7+1)%50;
i7=b;j7[b]=a;k7||(k7=49==b)},nya=function(a){var b=j7;
if(b[0]){var c=i7,d=k7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.x)(a,function(f){f(e)})}while(d!=c);
j7=Array(50);i7=-1;k7=!1}},pya=function(a,b){var c=((0,g.C)()-rya)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},l7=function(a){g.N.call(this);
this.D=a;this.screens=[]},sya=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},tya=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.ze)(a.screens,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=sya(a,b[d])||c;return c},uya=function(a,b){var c=a.screens.length;
a.screens=(0,g.ze)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},m7=function(a,b,c,d){g.N.call(this);
this.D=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.Ja=NaN},o7=function(a){l7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;n7(this);this.info("Initializing with "+h6(this.screens))},vya=function(a){if(a.screens.length){var b=(0,g.Hc)(a.screens,function(d){return d.id}),c=e7(a.u,"/pairing/get_lounge_token_batch");
f7(a.u,c,{screen_ids:b.join(",")},(0,g.w)(a.AF,a),(0,g.w)(a.zF,a))}},n7=function(a){var b=exa(kxa());
b=(0,g.ze)(b,function(c){return!c.uuid});
return tya(a,b)},p7=function(a,b){mxa((0,g.Hc)(a.screens,cxa));
b&&lxa()},r7=function(a,b){g.N.call(this);
this.D=b;var c=g.xs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.cb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;q7("Initialized with "+g.Ok(this.o))},wya=function(a,b,c){var d=e7(a.C,"/pairing/get_screen_availability");
f7(a.C,d,{lounge_token:b.token},(0,g.w)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.w)(function(){c(!1)},a))},s7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Ib(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(q7("Updated online screens: "+g.Ok(a.o)),a.o=b,a.T("screenChange"));xya(a)},t7=function(a){isNaN(a.A)||g.Oo(a.A);
a.A=g.Mo((0,g.w)(a.Au,a),0<a.B&&a.B<(0,g.C)()?2E4:1E4)},q7=function(a){h7("OnlineScreenService",a)},yya=function(a){var b={};
(0,g.x)(a.D(),function(c){c.token?b[c.token]=c.id:this.Yb("Requesting availability of screen w/o lounge token.")});
return b},xya=function(a){a=g.Ib(g.Cb(a.o,function(b){return b}));
g.tb(a);a.length?g.ws("yt-remote-online-screen-ids",a.join(","),60):g.ys("yt-remote-online-screen-ids")},u7=function(a){l7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};zya(this)},Bya=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.fe();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=v7(a,k);wya(a.o,l,function(m){e(m?l:null)})}else c?Aya(a,c,(0,g.w)(function(m){var n=v7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));wya(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},Cya=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},Aya=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.xq(e7(a.C,"/pairing/get_lounge_token_batch"),e)},Dya=function(a){a.screens=a.u.fe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.screens))},zya=function(a){w7(a);
a.u=new o7(a.C);a.u.subscribe("screenChange",(0,g.w)(a.IF,a));Dya(a);a.A=exa(g.xs("yt-remote-automatic-screen-cache")||[]);w7(a);a.info("Initializing automatic screens: "+h6(a.A));a.o=new r7(a.C,(0,g.w)(a.fe,a,!0));a.o.subscribe("screenChange",(0,g.w)(function(){this.T("onlineScreenChange")},a))},v7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.ws("yt-remote-automatic-screen-cache",(0,g.Hc)(a.A,cxa)));w7(a);a.B[b.uuid]=b.id;g.ws("yt-remote-device-id-map",a.B,31536E3);return b},w7=function(a){a.B=g.xs("yt-remote-device-id-map")||{}},x7=function(a,b,c){g.N.call(this);
this.S=c;this.J=a;this.u=b;this.A=null},y7=function(a,b){h7(a.S,b)},z7=function(a,b){x7.call(this,a,b,"CastSession");
this.o=null;this.B=0;this.D=(0,g.w)(this.pP,this);this.C=(0,g.w)(this.JN,this);this.B=g.Mo((0,g.w)(function(){Eya(this,null)},this),12E4)},Fya=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ok(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.w)(function(){y7(this,"Failed to send message: getMdxSessionStatus.")},a)):y7(a,"Sending yt message without session: "+g.Ok(b))},Eya=function(a,b){g.Oo(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.w)(a.Hp,a),d=(0,g.w)(a.me,a);a.Mx(b,c,d,5)}}else a.me(Error("Waiting for session status timed out."))},A7=function(a,b,c){x7.call(this,a,b,"DialSession");
this.B=this.H=null;this.R="";this.V=c;this.C=null;this.G=g.Ia;this.D=NaN;this.N=(0,g.w)(this.sP,this);this.o=g.Ia},Gya=function(a){a.o=a.J.hD(a.R,a.u.label,a.u.friendlyName,(0,g.w)(function(b){this.o=g.Ia;
this.Hp(b)},a),(0,g.w)(function(b){this.o=g.Ia;
this.me(b)},a))},Hya=function(a){var b={};
b.pairingCode=a.R;b.theme=a.V;if(a.C){var c=a.C.currentTime||0;b.v=a.C.videoId;b.t=c}oxa()&&(b.env_useStageMdx=1);return g.Ad(b)},B7=function(a,b){x7.call(this,a,b,"ManualSession");
this.o=g.Mo((0,g.w)(this.bk,this,null),150)},C7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.D=c||"cl";this.H=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.w)(this.AM,this)},Iya=function(a,b){return b?g.Za(a.A,function(c){return f6(b,c.label)},a):null},D7=function(a){h7("Controller",a)},lya=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},E7=function(a){return a.C||!!a.A.length||!!a.o},F7=function(a,b,c){b!=a.o&&(g.Le(a.o),(a.o=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.u):a.T("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.w)(a.jB,a,b)),b.A?a.T("yt-remote-cast2-session-change",b.A):c&&a.o.bk(null)):a.T("yt-remote-cast2-session-change",null))},Jya=function(a){var b=a.u.gD(),c=a.o&&a.o.u;
a=(0,g.Hc)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Iya(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Pya=function(a,b,c,d,e,f,k){Kya()?Lya(b,e,f,k)&&(H7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Mya(a,c):(window.__onGCastApiAvailable=function(l,m){l?Mya(a,c):(I7("Failed to load cast API: "+m),J7(!1),H7(!1),g.ys("yt-remote-cast-available"),g.ys("yt-remote-cast-receiver"),Nya(),c(!1))},d?g.Yo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?vxa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s6():(uxa(),r6(Oya.map(sxa))))):G7("Cannot initialize because not running Chrome")},Nya=function(){G7("dispose");
var a=K7();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);Qya(!1);g.Uo(L7);L7.length=0},M7=function(){return!!g.xs("yt-remote-cast-installed")},Rya=function(){var a=g.xs("yt-remote-cast-receiver");
return a?a.friendlyName:null},Sya=function(){G7("clearCurrentReceiver");
g.ys("yt-remote-cast-receiver")},Tya=function(){return M7()?K7()?K7().getCastSession():(I7("getCastSelector: Cast is not initialized."),null):(I7("getCastSelector: Cast API is not installed!"),null)},O7=function(){M7()?K7()?N7()?(G7("Requesting cast selector."),K7().requestSession()):(G7("Wait for cast API to be ready to request the session."),L7.push(g.To("yt-remote-cast2-api-ready",O7))):I7("requestCastSelector: Cast is not initialized."):I7("requestCastSelector: Cast API is not installed!")},P7=
function(a,b){N7()?K7().setConnectedScreenStatus(a,b):I7("setConnectedScreenStatus called before ready.")},Kya=function(){var a=0<=g.Nc.search(/ (CrMo|Chrome|CriOS)\//);
return g.wt||a},Uya=function(a,b){K7().init(a,b)},Lya=function(a,b,c,d){var e=!1;
K7()||(a=new C7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ws("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){G7("onReceiverSelected: "+f.friendlyName);
g.ws("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){G7("onReceiverResumed: "+f.friendlyName);
g.ws("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){G7("onSessionChange: "+g6(f));
f||g.ys("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
G7("cloudview.createSingleton_: "+e);return e},K7=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},Mya=function(a,b){J7(!0);
H7(!1);Uya(a,function(c){c?(Qya(!0),g.Vo("yt-remote-cast2-api-ready")):(I7("Failed to initialize cast API."),J7(!1),g.ys("yt-remote-cast-available"),g.ys("yt-remote-cast-receiver"),Nya());b(c)})},G7=function(a){h7("cloudview",a)},I7=function(a){h7("cloudview",a)},J7=function(a){G7("setCastInstalled_ "+a);
g.ws("yt-remote-cast-installed",a)},N7=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},Qya=function(a){G7("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H7=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},Q7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.D=this.G=0;this.o=null;this.hasNext=this.Af=!1;this.J=this.H=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},R7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Af=!1;a.hasNext=!1;a.G=0;a.D=(0,g.C)();a.C=0;a.u=0;a.H=0;a.J=0;a.B=NaN;a.A=!1},S7=function(a){return a.gb()?((0,g.C)()-a.D)/1E3:0},T7=function(a,b){a.G=b;
a.D=(0,g.C)()},U7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.D)/1E3+a.G;
case -1E3:return 0}return a.G},V7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&R7(a)},W7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Sb(a.o);b.hasPrevious=a.Af;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.D;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},Y7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.D=[];this.C=new gya;this.A=this.u=null;this.J=(0,g.w)(this.zK,this);this.G=(0,g.w)(this.sm,this);this.H=(0,g.w)(this.yK,this);this.R=(0,g.w)(this.JK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.xv,this),Vya(this))):c=3;0!=c&&(b?this.xv(c):g.Mo((0,g.w)(function(){this.xv(c)},this),0));
var d=Tya();d&&X7(this,d);this.subscribe("yt-remote-cast2-session-change",this.R)},Z7=function(a){return new Q7(a.B.getPlayerContextData())},Vya=function(a){(0,g.x)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.D.push(this.B.subscribe(b,g.Qa(this.xM,b),this))},a)},Wya=function(a){(0,g.x)(a.D,function(b){this.B.unsubscribeByKey(b)},a);
a.D.length=0},$7=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},b8=function(a,b,c){var d=Z7(a);
T7(d,c);-1E3!=d.playerState&&(d.playerState=b);a8(a,d)},c8=function(a,b,c){a.B.sendMessage(b,c)},a8=function(a,b){Wya(a);
a.B.setPlayerContextData(W7(b));Vya(a)},X7=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.G),a.sm(null));
a.A=b;a.A&&(h7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.G),a.A.media.length&&a.sm(a.A.media[0]))},Xya=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=Z7(a);b.contentId!=d.videoId&&h7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;T7(d,a.u.getEstimatedTime());a8(a,d)}else h7("CP","No cast media video. Ignoring state update.")},d8=function(a,b,c){return(0,g.w)(function(d){this.Yb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Yb("Retrying "+b+" using MDx browser channel."),c8(this,b,c))},a)},e8=function(a,b,c){g.N.call(this);
this.C=NaN;this.N=!1;this.H=this.G=this.J=this.R=NaN;this.S=[];this.B=this.D=this.A=this.Xa=this.o=null;this.W=a;this.S.push(g.ip(window,"beforeunload",(0,g.w)(this.sF,this)));this.u=[];this.Xa=new Q7;this.V=b.id;this.o=Yya(this,c);this.o.subscribe("handlerOpened",this.DK,this);this.o.subscribe("handlerClosed",this.AK,this);this.o.subscribe("handlerError",this.BK,this);this.o.subscribe("handlerMessage",this.CK,this);kya(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Xa.videoId;
g.zs()&&g.ws("yt-remote-session-video-id",d)},this)},f8=function(a){h7("conn",a)},Yya=function(a,b){return new b7(e7(a.W,"/bc"),b)},g8=function(a,b){a.T("proxyStateChange",b)},Zya=function(a){a.C=g.Mo((0,g.w)(function(){f8("Connecting timeout");
this.Cj(1)},a),2E4)},h8=function(a){g.Oo(a.C);
a.C=NaN},i8=function(a){g.Oo(a.R);
a.R=NaN},$ya=function(a){j8(a);
a.J=g.Mo((0,g.w)(function(){k8(this,"getNowPlaying")},a),2E4)},j8=function(a){g.Oo(a.J);
a.J=NaN},bza=function(a,b){b&&(h8(a),i8(a));
b==(c7(a.o)&&isNaN(a.C))?b&&(g8(a,1),k8(a,"getSubtitlesTrack")):b?(a.Kx()&&a.Xa.reset(),g8(a,1),k8(a,"getNowPlaying"),aza(a)):a.Cj(1)},cza=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Xa.videoId&&(g.Ob(b.params)?a.Xa.o=null:a.Xa.o=b.params,a.T("remotePlayerChange"))},dza=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Xa.listId=b.params.listId||a.Xa.listId;V7(a.Xa,c,d);a.T("remoteQueueChange")},fza=function(a,b){b.params=b.params||{};
dza(a,b);eza(a,b);a.T("autoplayDismissed")},eza=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
T7(a.Xa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Xa.playerState&&(c=-1E3);a.Xa.playerState=c;c=Number(b.params.loadedTime);a.Xa.J=isNaN(c)?0:c;c=Number(b.params.duration);a.Xa.H=isNaN(c)?0:c;c=a.Xa;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.Xa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Xa.playerState?$ya(a):j8(a);a.T("remotePlayerChange")},gza=function(a,b){if(-1E3!=
a.Xa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Xa.playerState=c;c=parseInt(b.params.currentTime,10);T7(a.Xa,isNaN(c)?0:c);a.T("remotePlayerChange")}},hza=function(a,b){var c="true"==b.params.muted;
a.Xa.volume=parseInt(b.params.volume,10);a.Xa.muted=c;a.T("remotePlayerChange")},iza=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",parseInt(b.params.timeout,10))},jza=function(a,b){var c="true"==b.params.hasNext;
a.Xa.Af="true"==b.params.hasPrevious;a.Xa.hasNext=c;a.T("previousNextChange")},aza=function(a){g.Oo(a.H);
a.H=g.Mo((0,g.w)(a.Cj,a,1),864E5)},k8=function(a,b,c){c?f8("Sending: action="+b+", params="+g.Ok(c)):f8("Sending: action="+b);
a.o.sendMessage(b,c)},l8=function(a){l7.call(this,"ScreenServiceProxy");
this.Bd=a;this.o=[];this.o.push(this.Bd.$_s("screenChange",(0,g.w)(this.nP,this)));this.o.push(this.Bd.$_s("onlineScreenChange",(0,g.w)(this.bM,this)))},oza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;gxa();o6();m8||(m8=new d7(b?b.loungeApiHost:void 0),oxa()&&(m8.o="/api/loungedev"));n8||(n8=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",n8,void 0));kza();var c=o8();if(!c){var d=new u7(m8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=o8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Pya(a,d,function(m){m?p8()&&P7(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.Ok(b)),r8.push(g.To("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),r8.push(g.To("yt-remote-cast2-receiver-selected",function(){s8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),r8.push(g.To("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),r8.push(g.To("yt-remote-cast2-session-change",lza)),r8.push(g.To("yt-remote-connection-change",function(m){m?P7(p8(),"YouTube TV"):t8()||(P7(null,null),Sya())})),a=u8(),b.isAuto&&(a.id+="#dial"),g.Co("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.Ok(a)),mza(a),c.start(),p8()||nza())},qza=function(){var a=pza();
M7()&&g.xs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},pza=function(){var a=o8().Bd.$_gos();
var b=v8();b&&w8()&&(j6(a,b)||a.push(b));return fxa(a)},x8=function(){var a=rza();
!a&&M7()&&Rya()&&(a={key:"cast-selector-receiver",name:Rya()});return a},rza=function(){var a=pza(),b=v8();
b||(b=t8());return g.Za(a,function(c){return b&&f6(b,c.key)?!0:!1})},v8=function(){var a=p8();
if(!a)return null;var b=o8().fe();return k6(b,a)},lza=function(a){q8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=v8();b&&b.id==a.id?P7(b.id,"YouTube TV"):(b&&y8(),z8(a,1))}else w8()&&y8()},y8=function(){N7()?K7().stopSession():I7("stopSession called before API ready.");
var a=w8();a&&(a.disconnect(1),A8(null))},B8=function(){var a=w8();
return!!a&&3!=a.getProxyState()},q8=function(a){h7("remote",a)},o8=function(){if(!C8){var a=g.Ha("yt.mdx.remote.screenService_");
C8=a?new l8(a):null}return C8},p8=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},sza=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},tza=function(){return g.Ha("yt.mdx.remote.connectData_")},s8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},w8=function(){return g.Ha("yt.mdx.remote.connection_")},A8=function(a){var b=w8();
s8(null);a||sza("");g.Fa("yt.mdx.remote.connection_",a,void 0);n8&&((0,g.x)(n8,function(c){c(a)}),n8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},t8=function(){var a=g.zs();
if(!a)return null;var b=o8();if(!b)return null;b=b.fe();return k6(b,a)},z8=function(a,b){p8();
v8()&&v8();if(D8)E8=a;else{sza(a.id);var c=new e8(m8,a,u8());c.connect(b,tza());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){w8()&&(w8(),A8(null))});
A8(c)}},nza=function(){var a=t8();
a?(q8("Resume connection to: "+g6(a)),z8(a,0)):(p6(),Sya(),q8("Skipping connecting because no session screen found."))},kza=function(){var a=u8();
if(g.Ob(a)){a=n6();var b=g.xs("yt-remote-session-name")||"",c=g.xs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},u8=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},mza=function(a){a?(g.ws("yt-remote-session-app",a.app),g.ws("yt-remote-session-name",a.name)):(g.ys("yt-remote-session-app"),g.ys("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.z.call(this);
var d=this;this.module=a;this.K=b;this.Sa=c;this.events=new g.zr(this);this.J=this.events.M(this.K,"onVolumeChange",this.JA);this.B=!1;this.suggestion=null;this.C=new g.FC(64);this.o=new g.H(this.pC,500,this);this.u=new g.H(this.qC,1E3,this);this.G=new t6(this.QO,0,this);this.A={};this.H=new g.H(this.SC,1E3,this);this.D=new u6(this.seekTo,1E3,this);this.R=g.Ia;g.A(this,this.events);this.events.M(b,"onCaptionsTrackListChanged",this.yL);this.events.M(b,"captionschanged",this.xK);this.events.M(b,"captionssettingschanged",
this.rC);this.events.M(b,"videoplayerreset",this.Ip);this.events.M(b,"mdxautoplaycancel",function(){d.Sa.Xw()});
a=this.Sa;a.ha();a.subscribe("proxyStateChange",this.dB,this);a.subscribe("remotePlayerChange",this.ym,this);a.subscribe("remoteQueueChange",this.Ip,this);a.subscribe("previousNextChange",this.ZA,this);a.subscribe("nowAutoplaying",this.VA,this);a.subscribe("autoplayDismissed",this.tA,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.G);g.A(this,this.H);g.A(this,this.D);this.rC();this.Ip();this.ym()},uza=function(a){a.Sb(0);
a.o.stop();G8(a,new g.FC(64))},I8=function(a,b){if(H8(a)&&!a.B){var c=null;
b&&(c={style:a.K.getSubtitlesUserSettings()},g.Ub(c,b));a.Sa.eD(a.K.getVideoData(1).videoId,c);a.A=Z7(a.Sa).o}},J8=function(a,b){var c=a.K.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.K.getVideoData(1);a.Sa.playVideo(c.videoId,b,d,e,c.playerParams,c.Cf,Twa(c));G8(a,new g.FC(1))},vza=function(a,b){if(b){var c=a.K.getOption("captions","tracklist",{ky:1});
c&&c.length?(a.K.setOption("captions","track",b),a.B=!1):(a.K.loadModule("captions"),a.B=!0)}else a.K.setOption("captions","track",{})},H8=function(a){return Z7(a.Sa).videoId===a.K.getVideoData(1).videoId},G8=function(a,b){a.u.stop();
var c=a.C;if(!g.LC(c,b)){var d=g.U(b,2);d!==g.U(a.C,2)&&g.cT(a.K.app,d);a.C=b;wza(a.module,c,b)}},K8=function(){g.Q.call(this,{F:"div",
I:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},L:[{F:"div",I:"ytp-mdx-manual-pairing-popup-dialog-inner-content",L:[{F:"div",I:"ytp-mdx-manual-pairing-popup-title",X:"Connecting to your TV on web using a code will be going away soon"},{F:"div",I:"ytp-mdx-manual-pairing-popup-buttons",L:[{F:"button",Z:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],X:"Learn more"},{F:"button",Z:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],X:"OK"}]}]}]});this.u=new g.wN(this,250);this.learnMoreButton=
this.o["ytp-mdx-manual-pairing-popup-learn-more"];this.okButton=this.o["ytp-mdx-manual-pairing-popup-ok"];g.A(this,this.u);this.M(this.learnMoreButton,"click",this.A);this.M(this.okButton,"click",this.B)},L8=function(){g.Q.call(this,{F:"div",
I:"ytp-mdx-popup-dialog",P:{role:"dialog"},L:[{F:"div",I:"ytp-mdx-popup-dialog-inner-content",L:[{F:"div",I:"ytp-mdx-popup-title",X:"You're signed out"},{F:"div",I:"ytp-mdx-popup-description",X:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{F:"div",I:"ytp-mdx-privacy-popup-buttons",L:[{F:"button",Z:["ytp-button","ytp-mdx-privacy-popup-cancel"],X:"Cancel"},{F:"button",Z:["ytp-button","ytp-mdx-privacy-popup-confirm"],
X:"Confirm"}]}]}]});this.u=new g.wN(this,250);this.cancelButton=this.o["ytp-mdx-privacy-popup-cancel"];this.confirmButton=this.o["ytp-mdx-privacy-popup-confirm"];g.A(this,this.u);this.M(this.cancelButton,"click",this.A);this.M(this.confirmButton,"click",this.B)},M8=function(a){g.Q.call(this,{F:"div",
I:"ytp-remote",L:[{F:"div",I:"ytp-remote-display-status",L:[{F:"div",I:"ytp-remote-display-status-icon",L:[g.QM()]},{F:"div",I:"ytp-remote-display-status-text",X:"{{statustext}}"}]}]});this.api=a;this.u=new g.wN(this,250);g.A(this,this.u);this.M(a,"presentingplayerstatechange",this.A);xza(this,g.gL(a))},xza=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.xM("Error on $RECEIVER_NAME",c):b.gb()||g.U(b,4)?g.xM("Playing on $RECEIVER_NAME",c):g.xM("Connected to $RECEIVER_NAME",c);a.oa("statustext",c);a.u.show()}else a.u.hide()},N8=function(a,b){g.pP.call(this,"Play on",0,a,b);
this.K=a;this.Uh={};this.M(a,"onMdxReceiversChange",this.D);this.M(a,"presentingplayerstatechange",this.D);this.D()},O8=function(a){g.ML.call(this,a);
this.bf={key:i6(),name:"This computer"};this.ae=null;this.subscriptions=[];this.lu=this.Sa=null;this.Uh=[this.bf];this.fh=this.bf;this.Jb=new g.FC(64);this.Cy=0;this.Tc=-1;this.ck=null;this.zm=this.Po=!1;this.gj=this.Ek=null;if(!g.Yy(this.player.O())){a=this.player;var b=g.cC(a);b&&(b=b.km())&&(b=new N8(a,b),g.A(this,b));b=new M8(a);g.A(this,b);g.AL(a,b.element,4);this.Ek=new L8;g.A(this,this.Ek);g.AL(a,this.Ek.element,4);g.O(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.ck=new K8,g.A(this,this.ck),g.AL(a,this.ck.element,4));this.zm=!!t8();this.Po=!!g.xs("yt-remote-manual-pairing-warning-shown")}},P8=function(a){a.gj&&(a.player.removeEventListener("presentingplayerstatechange",a.gj),a.gj=null)},wza=function(a,b,c){a.Jb=c;
a.player.T("presentingplayerstatechange",new g.hH(c,b))},yza=function(a,b,c){var d=!1;
1===b?d=!a.zm:2===b&&(d=!a.Po);d&&g.jH(c,8)&&(a.player.pauseVideo(),P8(a))},Q8=function(a,b){if(b.key!==a.fh.key)if(b.key===a.bf.key)y8();
else{if(a.ck&&!a.Po&&b!==a.bf&&"cast-selector-receiver"!==b.key&&g.gz(a.player.O()))zza(a);else{var c;(c=!g.O(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.zm||!a.Ek);(c?0:g.gz(a.player.O())||g.kz(a.player.O()))&&Aza(a)}a.fh=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.O(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ca(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Cf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Twa(c))&&(d.locationInfo=c);c=d}q8("Connecting to: "+g.Ok(b));"cast-selector-receiver"==b.key?(s8(c||null),c=
c||null,N7()?K7().setLaunchParams(c):I7("setLaunchParams called before ready.")):!c&&B8()&&p8()==b.key?c6("yt-remote-connection-change",!0):(y8(),s8(c||null),c=o8().fe(),(c=k6(c,b.key))&&z8(c,1))}},Aza=function(a){g.gL(a.player).gb()?a.player.pauseVideo():(a.gj=function(b){yza(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.gj));
a.Ek&&a.Ek.Ub();w8()||(D8=!0)},zza=function(a){g.gL(a.player).gb()?a.player.pauseVideo():(a.gj=function(b){yza(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.gj));
a.ck&&a.ck.Ub();w8()||(D8=!0)},Exa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H6={"'":"\\'"},Bza={},bxa={RP:"atp",ES:"ska",pS:"que",IR:"mus",DS:"sus",TQ:"dsp",xS:"seq"},q6,m6="",txa=pxa("loadCastFramework")||pxa("loadCastApplicationFramework"),Oya=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(t6,g.z);g.h=t6.prototype;g.h.pF=function(a){this.B=arguments;this.o=!1;this.Ja?this.A=(0,g.C)()+this.Cd:this.Ja=g.Yf(this.C,this.Cd)};
g.h.stop=function(){this.Ja&&(g.v.clearTimeout(this.Ja),this.Ja=null);this.A=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.D.apply(null,this.B)))};
g.h.Y=function(){this.stop();t6.Mb.Y.call(this)};
g.h.qF=function(){this.A?(this.Ja=g.Yf(this.C,this.A-(0,g.C)()),this.A=null):(this.Ja=null,this.u?this.o=!0:(this.o=!1,this.D.apply(null,this.B)))};g.r(u6,g.z);g.h=u6.prototype;g.h.Ry=function(a){this.A=arguments;this.Ja||this.u?this.o=!0:v6(this)};
g.h.stop=function(){this.Ja&&(g.v.clearTimeout(this.Ja),this.Ja=null,this.o=!1,this.A=null)};
g.h.pause=function(){this.u++};
g.h.resume=function(){this.u--;this.u||!this.o||this.Ja||(this.o=!1,v6(this))};
g.h.Y=function(){g.z.prototype.Y.call(this);this.stop()};x6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};y6.prototype.o=null;y6.prototype.getOptions=function(){var a;(a=this.o)||(a={},xxa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var R8;g.Sa(wxa,y6);R8=new wxa;g.h=z6.prototype;g.h.Fi=null;g.h.kf=!1;g.h.Vk=null;g.h.tv=null;g.h.Jk=null;g.h.Nj=null;g.h.Yg=null;g.h.Vh=null;g.h.hj=null;g.h.Nc=null;g.h.Ym=0;g.h.qf=null;g.h.Aq=null;g.h.qh=null;g.h.Kl=-1;g.h.eC=!0;g.h.ni=!1;g.h.us=0;g.h.Qp=null;var Cxa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.XN=function(a){a=a.target;var b=this.Qp;b&&3==Q6(a)?b.Ry():this.bD(a)};
g.h.bD=function(a){try{if(a==this.Nc)a:{var b=Q6(this.Nc),c=this.Nc.D,d=this.Nc.getStatus();if(g.me&&!g.Qd(10)||g.oe&&!g.Pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ah&&!S6(this.Nc))break a;this.ni||4!=b||7==c||(8==c||0>=d?this.o.gf(3):this.o.gf(2));J6(this);var e=this.Nc.getStatus();this.Kl=e;var f=S6(this.Nc);(this.kf=200==e)?(4==b&&F6(this),this.D?(Dxa(this,b,f),g.Ah&&this.kf&&3==b&&(this.B.na(this.u,"tick",this.QN),this.u.start())):E6(this,f),this.kf&&!this.ni&&(4==b?this.o.po(this):(this.kf=
!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qh=3,D6(13)):(this.qh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Nc&&S6(this.Nc)}finally{}};
g.h.QN=function(){var a=Q6(this.Nc),b=S6(this.Nc);this.Ym<b.length&&(J6(this),Dxa(this,a,b),this.kf&&4!=a&&B6(this))};
g.h.tN=function(a){I6((0,g.w)(this.sN,this,a),0)};
g.h.sN=function(a){this.ni||(J6(this),E6(this,a),B6(this))};
g.h.mB=function(a){I6((0,g.w)(this.rN,this,a),0)};
g.h.rN=function(a){this.ni||(F6(this),this.kf=a,this.o.po(this),this.o.gf(4))};
g.h.cancel=function(){this.ni=!0;F6(this)};
g.h.BN=function(){this.Vk=null;var a=(0,g.C)();0<=a-this.tv?(2!=this.Nj&&this.o.gf(3),F6(this),this.qh=2,D6(18),G6(this)):Gxa(this,this.tv-a)};
g.h.getLastError=function(){return this.qh};g.h=Jxa.prototype;g.h.rs=null;g.h.Ud=null;g.h.Rp=!1;g.h.Ux=null;g.h.Vn=null;g.h.Ts=null;g.h.ts=null;g.h.ye=null;g.h.wg=-1;g.h.Jl=null;g.h.kl=null;g.h.connect=function(a){this.ts=a;a=L6(this.o,null,this.ts);D6(3);this.Ux=(0,g.C)();var b=this.o.H;null!=b?(this.Jl=b[0],(this.kl=b[1])?(this.ye=1,Kxa(this)):(this.ye=2,N6(this))):($5(a,"MODE","init"),this.Ud=new z6(this,void 0,void 0,void 0),this.Ud.Fi=this.rs,A6(this.Ud,a,!1,null,!0),this.ye=0)};
g.h.pE=function(a){if(a)this.ye=2,N6(this);else{D6(4);var b=this.o;b.zf=b.bh.wg;Z6(b,9)}a&&this.gf(2)};
g.h.yr=function(a){return this.o.yr(a)};
g.h.abort=function(){this.Ud&&(this.Ud.cancel(),this.Ud=null);this.wg=-1};
g.h.Tx=function(){return!1};
g.h.eB=function(a,b){this.wg=a.Kl;if(0==this.ye)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.zf=this.wg;Z6(c,2);return}this.Jl=c[0];this.kl=c[1]}else c=this.o,c.zf=this.wg,Z6(c,2);else if(2==this.ye)if(this.Rp)D6(7),this.Ts=(0,g.C)();else if("11111"==b){if(D6(6),this.Rp=!0,this.Vn=(0,g.C)(),c=this.Vn-this.Ux,!g.me||g.Qd(10)||500>c)this.wg=200,this.Ud.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.Vn=this.Ts=(0,g.C)(),this.Rp=!1};
g.h.po=function(){this.wg=this.Ud.Kl;if(this.Ud.kf)0==this.ye?this.kl?(this.ye=1,Kxa(this)):(this.ye=2,N6(this)):2==this.ye&&((!g.me||g.Qd(10)?!this.Rp:200>this.Ts-this.Vn)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.ye?D6(9):2==this.ye&&D6(10);var a=this.o;this.Ud.getLastError();a.zf=this.wg;Z6(a,2)}};
g.h.Nm=function(){return this.o.Nm()};
g.h.isActive=function(){return this.o.isActive()};
g.h.gf=function(a){this.o.gf(a)};g.Sa(O6,g.lf);var Pxa=/^https?$/i,Cza=["POST","PUT"];g.h=O6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.J+"; newUri="+a);b=b?b.toUpperCase():"GET";this.J=a;this.B="";this.D=0;this.ga=b;this.W=!1;this.A=!0;this.o=this.V?yxa(this.V):yxa(R8);this.S=this.V?this.V.getOptions():R8.getOptions();this.o.onreadystatechange=(0,g.w)(this.aB,this);try{b6(R6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){b6(R6(this,"Error opening Xhr: "+f.message));Oxa(this,f);return}a=
c||"";var e=this.headers.clone();d&&Ywa(d,function(f,k){e.set(k,f)});
d=g.Za(e.ue(),Mxa);c=g.v.FormData&&a instanceof g.v.FormData;!g.cb(Cza,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.ba&&(this.o.withCredentials=this.ba);try{Rxa(this),0<this.G&&(this.N=Lxa(this.o),b6(R6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.N)),this.N?(this.o.timeout=this.G,this.o.ontimeout=(0,g.w)(this.Vx,this)):this.R=g.Yf(this.Vx,this.G,this)),b6(R6(this,"Sending request")),this.H=!0,this.o.send(a),this.H=!1}catch(f){b6(R6(this,"Send error: "+f.message)),Oxa(this,f)}};
g.h.Vx=function(){"undefined"!=typeof g.C1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.D=8,R6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.A&&(R6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.D=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.Y=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),P6(this,!0));O6.Mb.Y.call(this)};
g.h.aB=function(){this.ha()||(this.aa||this.H||this.C?Qxa(this):this.zM())};
g.h.zM=function(){Qxa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<Q6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.h=T6.prototype;g.h.Al=null;g.h.Od=null;g.h.jc=null;g.h.qs=null;g.h.Yn=null;g.h.rw=null;g.h.oo=null;g.h.rm=0;g.h.SJ=0;g.h.yd=null;g.h.ih=null;g.h.eg=null;g.h.wi=null;g.h.bh=null;g.h.yq=null;g.h.ak=-1;g.h.By=-1;g.h.zf=-1;g.h.Gj=0;g.h.wj=0;g.h.oi=8;var $6=new g.lf;g.Sa(Txa,g.Ne);g.Sa(Uxa,g.Ne);g.Sa(Vxa,g.Ne);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.qs=b;this.Al=c||{};d&&void 0!==e&&(this.Al.OSID=d,this.Al.OAID=e);this.D?(I6((0,g.w)(this.Lw,this,a),100),Zxa(this)):this.Lw(a)};
g.h.Lw=function(a){this.bh=new Jxa(this);this.bh.rs=null;this.bh.u=this.C;this.bh.connect(a)};
g.h.Tx=function(){return 0==this.o};
g.h.lB=function(a){this.ih=null;bya(this,a)};
g.h.kB=function(){this.eg=null;this.jc=new z6(this,this.A,"rpc",this.G);this.jc.Fi=null;this.jc.us=0;var a=this.rw.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.A);Y5(a,"CI",this.yq?"0":"1");Y5(a,"AID",this.ak);U6(this,a);if(!g.me||g.Qd(10))Y5(a,"TYPE","xmlhttp"),A6(this.jc,a,!0,this.oo,!1);else{Y5(a,"TYPE","html");var b=this.jc,c=!!this.oo;b.Nj=3;b.Yg=Z5(a.clone());Fxa(b,c)}};
g.h.eB=function(a,b){if(0!=this.o&&(this.jc==a||this.Od==a))if(this.zf=a.Kl,this.Od==a&&3==this.o)if(7<this.oi){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.eg){if(this.jc)if(this.jc.Jk+3E3<this.Od.Jk)W6(this),this.jc.cancel(),this.jc=null;else break a;Y6(this);D6(19)}}else this.By=c[1],0<this.By-this.ak&&37500>c[2]&&this.yq&&0==this.wj&&!this.wi&&(this.wi=I6((0,g.w)(this.uK,this),6E3));else Z6(this,11)}else b!=Bza.oQ.o&&Z6(this,11);else if(this.jc==
a&&W6(this),!g.kc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ak=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.oo=e[2],e=e[3],null!=e?this.oi=e:this.oi=6,this.o=3,this.yd&&this.yd.Hw(),this.rw=L6(this,this.Nm()?this.oo:null,this.qs),cya(this)):"stop"==e[0]&&Z6(this,7):3==this.o&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.yd&&this.yd.Gw(e),this.wj=0)}}};
g.h.uK=function(){null!=this.wi&&(this.wi=null,this.jc.cancel(),this.jc=null,Y6(this),D6(20))};
g.h.po=function(a){if(this.jc==a){W6(this);this.jc=null;var b=2}else if(this.Od==a)this.Od=null,b=1;else return;this.zf=a.Kl;if(0!=this.o)if(a.kf)1==b?(b=(0,g.C)()-a.Jk,$6.dispatchEvent(new Uxa($6,a.hj?a.hj.length:0,b,this.Gj)),V6(this),this.B.length=0):cya(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.zf)){if(d=1==b)this.Od||this.ih||1==this.o||2<=this.Gj?d=!1:(this.ih=I6((0,g.w)(this.lB,this,a),dya(this,this.Gj)),this.Gj++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,
5);break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.ME=function(a){if(!g.cb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.HO=function(a){a?D6(2):(D6(1),eya(this,8))};
g.h.yr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.ba=!1;return a};
g.h.isActive=function(){return!!this.yd&&this.yd.isActive(this)};
g.h.gf=function(a){$6.dispatchEvent(new Vxa($6,a))};
g.h.Nm=function(){return!(!g.me||g.Qd(10))};
g.h=fya.prototype;g.h.Hw=function(){};
g.h.Gw=function(){};
g.h.Fw=function(){};
g.h.mr=function(){};
g.h.rx=function(){return{}};
g.h.isActive=function(){return!0};g.h=gya.prototype;g.h.isEmpty=function(){return g.db(this.o)&&g.db(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.cb(this.o,a)||g.cb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Gra)(b,a);0<=c?(g.fb(b,c),b=!0):b=!1;return b||g.gb(this.u,a)};
g.h.Id=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa(a7,g.z);g.h=a7.prototype;g.h.mN=function(){this.Cd=Math.min(3E5,2*this.Cd);this.A();this.u&&this.start()};
g.h.start=function(){var a=this.Cd+15E3*Math.random();this.o.Va(a);this.u=(0,g.C)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Cd=5E3};g.Sa(b7,fya);g.h=b7.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Lh=function(a){return this.A.Gi(a)};
g.h.T=function(a,b){return this.A.T.apply(this.A,arguments)};
g.h.dispose=function(){this.Fb||(this.Fb=!0,g.Le(this.A),jya(this),g.Le(this.u),this.u=null)};
g.h.ha=function(){return this.Fb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.u.stop();this.C=a||null;this.B=b||0;a=this.R+"/test";b=this.R+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.yd=null);d.yd=this;this.o=d;e?this.o.connect(a,b,this.D,e.A,e.ak):c?this.o.connect(a,b,this.D,c.sessionId,c.arrayId):this.o.connect(a,b,this.D)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Ub(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):c7(this)&&$xa(this.o,c)};
g.h.Hw=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)$xa(this.o,a[b])}this.T("handlerOpened")};
g.h.Fw=function(a){var b=2==a&&401==this.o.zf;4==a||b||this.u.start();this.T("handlerError",a)};
g.h.mr=function(a){if(!this.u.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.rx=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.C&&g.Ub(a,this.C);return a};
g.h.Gw=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Yxa(this.o)):this.T("handlerMessage",new hya(a[0],a[1]))};
g.h.kO=function(){this.u.isActive();var a=this.o,b=0;a.jc&&b++;a.Od&&b++;0==b&&this.connect(this.C,this.B)};d7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
d7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
d7.prototype.C=function(a){a(Error("request timed out"))};var rya=(0,g.C)(),g7=null,j7=Array(50),i7=-1,k7=!1;g.Sa(l7,g.N);l7.prototype.fe=function(){return this.screens};
l7.prototype.contains=function(a){return!!j6(this.screens,a)};
l7.prototype.get=function(a){return a?k6(this.screens,a):null};
l7.prototype.info=function(a){h7(this.D,a)};g.r(m7,g.N);g.h=m7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ja)&&this.fD()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ja)||(g.Oo(this.Ja),this.Ja=NaN)};
g.h.Y=function(){this.stop();g.N.prototype.Y.call(this)};
g.h.fD=function(){this.Ja=NaN;this.o=g.xq(e7(this.D,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.w)(this.lP,this),onError:(0,g.w)(this.kP,this),ne:(0,g.w)(this.mP,this)})};
g.h.lP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.T("pairingComplete",new e6(c))};
g.h.kP=function(a){this.o=null;a.status&&404==a.status?this.u>=Dza.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=Dza[this.u],this.Ja=g.Mo((0,g.w)(this.fD,this),a),this.u++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.mP=function(){this.o=null;this.T("pairingFailed",Error("Server not responding"))};
var Dza=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(o7,l7);g.h=o7.prototype;g.h.start=function(){n7(this)&&this.T("screenChange");!g.xs("yt-remote-lounge-token-expiration")&&vya(this);g.Oo(this.o);this.o=g.Mo((0,g.w)(this.start,this),1E4)};
g.h.add=function(a,b){n7(this);sya(this,a);p7(this,!1);this.T("screenChange");b(a);a.token||vya(this)};
g.h.remove=function(a,b){var c=n7(this);uya(this,a)&&(p7(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.wq=function(a,b,c,d){var e=n7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,p7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.Y=function(){g.Oo(this.o);o7.Mb.Y.call(this)};
g.h.AF=function(a){n7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}p7(this,!b);b&&h7(this.D,"Missed "+b+" lounge tokens.")};
g.h.zF=function(a){h7(this.D,"Requesting lounge tokens failed: "+a)};g.r(r7,g.N);g.h=r7.prototype;g.h.start=function(){var a=parseInt(g.xs("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.C)()-144E5<a?0:a)?t7(this):(this.B=(0,g.C)()+3E5,g.ws("yt-remote-fast-check-period",this.B),this.Au())};
g.h.isEmpty=function(){return g.Ob(this.o)};
g.h.update=function(){q7("Updating availability on schedule.");var a=this.D(),b=g.Cb(this.o,function(c,d){return c&&!!k6(a,d)},this);
s7(this,b)};
g.h.Y=function(){g.Oo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.Y.call(this)};
g.h.Au=function(){g.Oo(this.A);this.A=NaN;this.u&&this.u.abort();var a=yya(this);if(a6(a)){var b=e7(this.C,"/pairing/get_screen_availability");this.u=f7(this.C,b,{lounge_token:g.Ib(a).join(",")},(0,g.w)(this.WM,this,a),(0,g.w)(this.VM,this))}else s7(this,{}),t7(this)};
g.h.WM=function(a,b){this.u=null;var c=g.Ib(yya(this));if(g.vb(c,g.Ib(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;s7(this,d);t7(this)}else this.Yb("Changing Screen set during request."),this.Au()};
g.h.VM=function(a){this.Yb("Screen availability failed: "+a);this.u=null;t7(this)};
g.h.Yb=function(a){h7("OnlineScreenService",a)};g.Sa(u7,l7);g.h=u7.prototype;g.h.start=function(){this.u.start();this.o.start();this.screens.length&&(this.T("screenChange"),this.o.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.u.add(a,b,c)};
g.h.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.h.wq=function(a,b,c,d){this.u.contains(a)?this.u.wq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,h7(this.D,a),d(Error(a)))};
g.h.fe=function(a){return a?this.screens:g.jb(this.screens,(0,g.ze)(this.A,function(b){return!this.contains(b)},this))};
g.h.gD=function(){return(0,g.ze)(this.fe(!0),function(a){return!!this.o.o[a.id]},this)};
g.h.hD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new m7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.w)(function(k){g.Le(f);d(v7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Le(f);e(k)});
f.start();return(0,g.w)(f.stop,f)};
g.h.oP=function(a,b,c,d){g.xq(e7(this.C,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.w)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Cya(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Cya(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(v7(this,k))},this),
onError:(0,g.w)(function(e){d(Error("pairing request failed: "+e.status))},this),
ne:(0,g.w)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.Le(this.u);g.Le(this.o);u7.Mb.Y.call(this)};
g.h.IF=function(){Dya(this);this.T("screenChange");this.o.update()};
u7.prototype.dispose=u7.prototype.dispose;g.Sa(x7,g.N);g.h=x7.prototype;g.h.Hp=function(a){this.A=a;this.T("sessionScreen",this.A)};
g.h.me=function(a){this.ha()||(a&&y7(this,""+a),this.A=null,this.T("sessionScreen",null))};
g.h.info=function(a){h7(this.S,a)};
g.h.jD=function(){return null};
g.h.Ku=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.w)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.w)(function(){y7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Ku("");x7.Mb.Y.call(this)};g.Sa(z7,x7);g.h=z7.prototype;g.h.Ju=function(a){if(this.o){if(this.o==a)return;y7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.D);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.o=a;this.o.addUpdateListener(this.D);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);Fya(this)};
g.h.bk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ok(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.w)(function(){this.me()},this),(0,g.w)(function(){this.me(Error("Failed to stop receiver app."))},this)):this.me(Error("Stopping cast device witout session."))};
g.h.Ku=g.Ia;g.h.Y=function(){this.info("disposeInternal");g.Oo(this.B);this.B=0;this.o&&(this.o.removeUpdateListener(this.D),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.o=null;z7.Mb.Y.call(this)};
g.h.JN=function(a,b){if(!this.ha())if(b){var c=w6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ok(c));switch(d){case "mdxSessionStatus":Eya(this,c.screenId);break;default:y7(this,"Unknown youtube message: "+d)}}else y7(this,"Unable to parse message.")}else y7(this,"No data in message.")};
g.h.Mx=function(a,b,c,d){Bya(this.J,this.u.label,a,this.u.friendlyName,(0,g.w)(function(e){e?b(e):0<=d?(y7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Mo((0,g.w)(this.Mx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.jD=function(){return this.o};
g.h.pP=function(a){this.ha()||a||(y7(this,"Cast session died."),this.me())};g.Sa(A7,x7);g.h=A7.prototype;g.h.Ju=function(a){this.B=a;this.B.addUpdateListener(this.N)};
g.h.bk=function(a){this.C=a;this.G()};
g.h.stop=function(){this.o();this.o=g.Ia;g.Oo(this.D);this.B?this.B.stop((0,g.w)(this.me,this,null),(0,g.w)(this.me,this,"Failed to stop DIAL device.")):this.me()};
g.h.Y=function(){this.o();this.o=g.Ia;g.Oo(this.D);this.B&&this.B.removeUpdateListener(this.N);this.B=null;A7.Mb.Y.call(this)};
g.h.sP=function(a){this.ha()||a||(y7(this,"DIAL session died."),this.o(),this.o=g.Ia,this.me())};
g.h.Fs=function(a){this.R=i6();if(this.C){var b=new chrome.cast.DialLaunchResponse(!0,Hya(this));a(b);Gya(this)}else this.G=(0,g.w)(function(){g.Oo(this.D);this.G=g.Ia;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Hya(this));a(c);Gya(this)},this),this.D=g.Mo((0,g.w)(function(){this.G()},this),100)};
g.h.cG=function(a,b,c){Bya(this.J,this.H.receiver.label,a,this.u.friendlyName,(0,g.w)(function(d){d&&d.token?(this.Hp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Fs(b,c)},this),(0,g.w)(function(d){y7(this,"Failed to get DIAL screen: "+d);
this.Fs(b,c)},this))};g.Sa(B7,x7);B7.prototype.stop=function(){this.me()};
B7.prototype.Ju=g.Ia;B7.prototype.bk=function(){g.Oo(this.o);this.o=NaN;var a=k6(this.J.fe(),this.u.label);a?this.Hp(a):this.me(Error("No such screen"))};
B7.prototype.Y=function(){g.Oo(this.o);this.o=NaN;B7.Mb.Y.call(this)};g.Sa(C7,g.N);g.h=C7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.w)(this.EM,this);c=new chrome.cast.ApiConfig(c,(0,g.w)(this.hB,this),f,d,e);c.customDialLaunchCallback=(0,g.w)(this.QK,this);chrome.cast.initialize(c,(0,g.w)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),oya(),this.u.subscribe("onlineScreenChange",(0,g.w)(this.iD,this)),this.A=Jya(this),chrome.cast.setCustomReceivers(this.A,g.Ia,(0,g.w)(function(k){this.Yb("Failed to set initial custom receivers: "+g.Ok(k))},this)),this.T("yt-remote-cast2-availability-change",E7(this)),b(!0))},this),(0,g.w)(function(k){this.Yb("Failed to initialize API: "+g.Ok(k));
b(!1)},this))};
g.h.rO=function(a,b){D7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.A;if(!a||c&&c.id!=a)D7("Unsetting old screen status: "+this.o.u.friendlyName),F7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.fe(),a);if(!c){D7("setConnectedScreenStatus: Unknown screen.");return}var d=Iya(this,c);d||(D7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ia,(0,g.w)(function(e){this.Yb("Failed to set initial custom receivers: "+g.Ok(e))},this)));
D7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);F7(this,new B7(this.u,d),!0)}this.o.Ku(b)}else D7("setConnectedScreenStatus: no screen.")};
g.h.sO=function(a){this.ha()?this.Yb("Setting connection data on disposed cast v2"):this.o?this.o.bk(a):this.Yb("Setting connection data without a session")};
g.h.rP=function(){this.ha()?this.Yb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),F7(this,null)):D7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.w)(this.hB,this),(0,g.w)(this.ZM,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.w)(this.iD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=lya,b=g.Ha("yt.mdx.remote.debug.handlers_");g.gb(b||[],a);g.Le(this.o);C7.Mb.Y.call(this)};
g.h.Yb=function(a){h7("Controller",a)};
g.h.jB=function(a,b){this.o==a&&(b||F7(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.AM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),D7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)D7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{D7("onReceiverAction_: Casting to active receiver.");this.o.A&&this.T("yt-remote-cast2-session-change",this.o.A);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:F7(this,
new B7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:F7(this,new A7(this.u,a,this.D));break;case chrome.cast.ReceiverType.CAST:F7(this,new z7(this.u,a));break;default:this.Yb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Yb("Stopping receiver w/o session: "+a.friendlyName)}else this.Yb("onReceiverAction_ called without receiver.")};
g.h.QK=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Yb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Yb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.A)return D7("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.o.A),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Yb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);F7(this,new A7(this.u,b,this.D))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.w)(b.cG,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.w)(b.Fs,b))};
g.h.hB=function(a){if(!this.ha()){D7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)D7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),F7(this,new z7(this.u,b),!0);else{this.Yb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.fe(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(D7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Le(this.o),this.o=new z7(this.u,b),this.o.subscribe("sessionScreen",(0,g.w)(this.jB,this,this.o)),this.o.bk(null));this.o.Ju(a)}}};
g.h.qP=function(){return this.o?this.o.jD():null};
g.h.ZM=function(a){this.ha()||(this.Yb("Failed to estabilish a session: "+g.Ok(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&F7(this,null))};
g.h.EM=function(a){D7("Receiver availability updated: "+a);if(!this.ha()){var b=E7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;E7(this)!=b&&this.T("yt-remote-cast2-availability-change",E7(this))}};
g.h.iD=function(){this.ha()||(this.A=Jya(this),D7("Updating custom receivers: "+g.Ok(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ia,(0,g.w)(function(){this.Yb("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",E7(this)))};
C7.prototype.setLaunchParams=C7.prototype.sO;C7.prototype.setConnectedScreenStatus=C7.prototype.rO;C7.prototype.stopSession=C7.prototype.rP;C7.prototype.getCastSession=C7.prototype.qP;C7.prototype.requestSession=C7.prototype.requestSession;C7.prototype.init=C7.prototype.init;C7.prototype.dispose=C7.prototype.dispose;var L7=[];g.h=Q7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";R7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Af=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.D=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.h.gb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.A?this.H+S7(this):this.H};
g.h.clone=function(){return new Q7(W7(this))};g.r(Y7,g.N);g.h=Y7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ia,d8(this,"play")):c8(this,"play"),b8(this,1,U7(Z7(this))),this.T("remotePlayerChange")):$7(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ia,d8(this,"pause")):c8(this,"pause"),b8(this,2,U7(Z7(this))),this.T("remotePlayerChange")):$7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=Z7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.gb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,d8(this,"seekTo",{newTime:a}))}else c8(this,"seekTo",{newTime:a});b8(this,3,a);this.T("remotePlayerChange")}else $7(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ia,d8(this,"stopVideo")):c8(this,"stopVideo");var a=Z7(this);a.index=-1;a.videoId="";R7(a);a8(this,a);this.T("remotePlayerChange")}else $7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=Z7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.w)(function(){h7("CP","set receiver volume: "+d)},this),(0,g.w)(function(){this.Yb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.w)(function(){h7("CP","set receiver muted: "+b)},this),(0,g.w)(function(){this.Yb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);c8(this,"setVolume",e)}c.muted=b;c.volume=a;a8(this,c)}else $7(this,g.Qa(this.setVolume,a,b))};
g.h.eD=function(a,b){if(1==this.o){var c=Z7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ok(b.style),g.Ub(d,c.o));c8(this,"setSubtitlesTrack",d);a8(this,c)}else $7(this,g.Qa(this.eD,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();c8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=Z7(this);d.audioTrackId=c;a8(this,d)}else $7(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=Z7(this);c=c||0;var m={videoId:a,currentIndex:c};V7(l,a,c);void 0!==b&&(T7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Ok(k));c8(this,"setPlaylist",m);d||a8(this,l)};
g.h.Np=function(a,b){if(1==this.o){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"previous")}else $7(this,g.Qa(this.Np,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"next")}else $7(this,g.Qa(this.nextVideo,a,b))};
g.h.Xw=function(){1==this.o?c8(this,"dismissAutoplay"):$7(this,this.Xw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.T("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.h.Y=function(){Wya(this);this.B=null;this.C.clear();X7(this,null);g.N.prototype.Y.call(this)};
g.h.xv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.db(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.xM=function(a,b){this.T(a,b)};
g.h.zK=function(a){if(!a)this.sm(null),X7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=Z7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,a8(this,b)}};
g.h.sm=function(a){h7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.H);if(this.u=a)this.u.addUpdateListener(this.H),Xya(this),this.T("remotePlayerChange")};
g.h.yK=function(a){a?(Xya(this),this.T("remotePlayerChange")):this.sm(null)};
g.h.Xu=function(){c8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.JK=function(){var a=Tya();a&&X7(this,a)};
g.h.Yb=function(a){h7("CP",a)};g.r(e8,g.N);g.h=e8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Xa.listId=c);this.Xa.videoId=d;this.Xa.index=k||0;this.Xa.state=3;T7(this.Xa,m);this.B="UNSUPPORTED";f8("Connecting with setPlaylist and params: "+g.Ok(l));this.o.connect({method:"setPlaylist",
params:g.Ok(l)},a,jxa())}else f8("Connecting without params"),this.o.connect({},a,jxa());Zya(this)};
g.h.dispose=function(){this.ha()||(this.T("beforeDispose"),g8(this,3));g.N.prototype.dispose.call(this)};
g.h.Y=function(){h8(this);j8(this);i8(this);g.Oo(this.G);this.G=NaN;g.Oo(this.H);this.H=NaN;this.A=null;g.jp(this.S);this.S.length=0;this.o.dispose();g.N.prototype.Y.call(this);this.B=this.D=this.u=this.Xa=this.o=null};
g.h.sF=function(){this.Cj(2)};
g.h.DK=function(){f8("Channel opened");this.N&&(this.N=!1,i8(this),this.R=g.Mo((0,g.w)(function(){f8("Timing out waiting for a screen.");this.Cj(1)},this),15E3));
nxa(iya(this.o),this.V)};
g.h.AK=function(){f8("Channel closed");isNaN(this.C)?p6(!0):p6();this.dispose()};
g.h.BK=function(a){p6();isNaN(this.Fl())?(f8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,f8("Channel error: "+a+" with reconnection in "+this.Fl()+" ms"),g8(this,2))};
g.h.CK=function(a){a.params?f8("Received: action="+a.action+", params="+g.Ok(a.params)):f8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=w6(a.params.devices);this.u=(0,g.Hc)(a,function(c){return new d6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
bza(this,a);break;case "loungeScreenDisconnected":g.ib(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
bza(this,!1);break;case "remoteConnected":var b=new d6(w6(a.params.device));g.Za(this.u,function(c){return b?c.id==b.id:!1})||Uwa(this.u,b);
break;case "remoteDisconnected":b=new d6(w6(a.params.device));g.ib(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":dza(this,a);break;case "nowPlaying":fza(this,a);break;case "onStateChange":eza(this,a);break;case "onAdStateChange":gza(this,a);break;case "onVolumeChanged":hza(this,a);break;case "onSubtitlesTrackChanged":cza(this,a);break;case "nowAutoplaying":iza(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.T("autoplayModeChange",this.B);"DISABLED"==this.B&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":jza(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:f8("Unrecognized action: "+a.action)}};
g.h.gO=function(){if(this.A){var a=this.A;this.A=null;this.Xa.videoId!=a&&k8(this,"getNowPlaying")}};
g.h.jF=function(){var a=3;this.ha()||(a=0,isNaN(this.Fl())?c7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.h.Cj=function(a){f8("Disconnecting with "+a);h8(this);this.T("beforeDisconnect",a);1==a&&p6();jya(this.o,a);this.dispose()};
g.h.iF=function(){var a=this.Xa;this.A&&(a=this.Xa.clone(),V7(a,this.A,a.index));return W7(a)};
g.h.tO=function(a){var b=new Q7(a);b.videoId&&b.videoId!=this.Xa.videoId&&(this.A=b.videoId,g.Oo(this.G),this.G=g.Mo((0,g.w)(this.gO,this),5E3));var c=[];this.Xa.listId==b.listId&&this.Xa.videoId==b.videoId&&this.Xa.index==b.index||c.push("remoteQueueChange");this.Xa.playerState==b.playerState&&this.Xa.volume==b.volume&&this.Xa.muted==b.muted&&U7(this.Xa)==U7(b)&&g.Ok(this.Xa.o)==g.Ok(b.o)||c.push("remotePlayerChange");this.Xa.reset(a);(0,g.x)(c,function(d){this.T(d)},this)};
g.h.Kx=function(){var a=this.o.D.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Fl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.h.XE=function(){return this.B||"UNSUPPORTED"};
g.h.YE=function(){return this.D||""};
g.h.jP=function(){if(!isNaN(this.Fl())){var a=this.o.u;g.zn(a.o);a.start()}};
g.h.oO=function(a,b){k8(this,a,b);aza(this)};
e8.prototype.subscribe=e8.prototype.subscribe;e8.prototype.unsubscribeByKey=e8.prototype.Lh;e8.prototype.getProxyState=e8.prototype.jF;e8.prototype.disconnect=e8.prototype.Cj;e8.prototype.getPlayerContextData=e8.prototype.iF;e8.prototype.setPlayerContextData=e8.prototype.tO;e8.prototype.getOtherConnectedRemoteId=e8.prototype.Kx;e8.prototype.getReconnectTimeout=e8.prototype.Fl;e8.prototype.getAutoplayMode=e8.prototype.XE;e8.prototype.getAutoplayVideoId=e8.prototype.YE;e8.prototype.reconnect=e8.prototype.jP;
e8.prototype.sendMessage=e8.prototype.oO;g.r(l8,l7);g.h=l8.prototype;g.h.fe=function(a){return this.Bd.$_gs(a)};
g.h.contains=function(a){return!!this.Bd.$_c(a)};
g.h.get=function(a){return this.Bd.$_g(a)};
g.h.start=function(){this.Bd.$_st()};
g.h.add=function(a,b,c){this.Bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Bd.$_r(a,b,c)};
g.h.wq=function(a,b,c,d){this.Bd.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.o.length;a<b;++a)this.Bd.$_ubk(this.o[a]);this.o.length=0;this.Bd=null;l7.prototype.Y.call(this)};
g.h.nP=function(){this.T("screenChange")};
g.h.bM=function(){this.T("onlineScreenChange")};
u7.prototype.$_st=u7.prototype.start;u7.prototype.$_gspc=u7.prototype.oP;u7.prototype.$_gsppc=u7.prototype.hD;u7.prototype.$_c=u7.prototype.contains;u7.prototype.$_g=u7.prototype.get;u7.prototype.$_a=u7.prototype.add;u7.prototype.$_un=u7.prototype.wq;u7.prototype.$_r=u7.prototype.remove;u7.prototype.$_gs=u7.prototype.fe;u7.prototype.$_gos=u7.prototype.gD;u7.prototype.$_s=u7.prototype.subscribe;u7.prototype.$_ubk=u7.prototype.Lh;var E8=null,D8=!1,m8=null,n8=null,C8=null,r8=[];g.r(F8,g.z);g.h=F8.prototype;g.h.Y=function(){g.z.prototype.Y.call(this);this.o.stop();this.u.stop();this.G.stop();this.R();var a=this.Sa;a.unsubscribe("proxyStateChange",this.dB,this);a.unsubscribe("remotePlayerChange",this.ym,this);a.unsubscribe("remoteQueueChange",this.Ip,this);a.unsubscribe("previousNextChange",this.ZA,this);a.unsubscribe("nowAutoplaying",this.VA,this);a.unsubscribe("autoplayDismissed",this.tA,this);this.Sa=this.module=null};
g.h.oz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Sa.o)if(H8(this)){if(!Z7(this.Sa).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Z7(this.Sa).gb()?this.Sa.pause():this.Sa.play();break;case "control_play":this.Sa.play();break;case "control_pause":this.Sa.pause();break;case "control_seek":this.D.Ry(c[0],c[1]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.K.getCurrentTime();J8(this,0===c?void 0:c);break;case "control_seek":J8(this,c[0]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.h.xK=function(a){this.G.pF(a)};
g.h.QO=function(a){this.oz("control_subtitles_set_track",g.Ob(a)?null:a)};
g.h.rC=function(){var a=this.K.getOption("captions","track");g.Ob(a)||I8(this,a)};
g.h.Sb=function(a){this.module.Sb(a,this.K.getVideoData().lengthSeconds)};
g.h.JA=function(a){if(H8(this)){this.Sa.unsubscribe("remotePlayerChange",this.ym,this);var b=Math.round(a.volume);a=!!a.muted;var c=Z7(this.Sa);if(b!==c.volume||a!==c.muted)this.Sa.setVolume(b,a),this.H.start();this.Sa.subscribe("remotePlayerChange",this.ym,this)}};
g.h.yL=function(){g.Ob(this.A)||vza(this,this.A);this.B=!1};
g.h.dB=function(a,b){this.u.stop();2===b&&this.qC()};
g.h.ym=function(){if(H8(this)){this.o.stop();var a=Z7(this.Sa);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.Tc=1;break;case 1082:case 1083:this.module.Tc=0;break;default:this.module.Tc=-1}switch(a.playerState){case 1081:case 1:G8(this,new g.FC(8));this.pC();break;case 1085:case 3:G8(this,new g.FC(9));break;case 1083:case 0:G8(this,new g.FC(2));this.D.stop();this.Sb(this.K.getVideoData().lengthSeconds);break;case 1084:G8(this,new g.FC(4));break;case 2:G8(this,new g.FC(4));
this.Sb(U7(a));break;case -1:G8(this,new g.FC(64));break;case -1E3:G8(this,new g.FC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=Z7(this.Sa).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,vza(this,a));a=Z7(this.Sa);-1===a.volume||Math.round(this.K.getVolume())===a.volume&&this.K.isMuted()===a.muted||this.H.isActive()||this.SC()}else uza(this)};
g.h.ZA=function(){this.K.T("mdxpreviousnextchange")};
g.h.Ip=function(){H8(this)||uza(this)};
g.h.VA=function(a){isNaN(a)||this.K.T("mdxnowautoplaying",a)};
g.h.tA=function(){this.K.T("mdxautoplaycanceled")};
g.h.setAudioTrack=function(a){H8(this)&&this.Sa.setAudioTrack(this.K.getVideoData(1).videoId,a)};
g.h.seekTo=function(a,b){-1===Z7(this.Sa).playerState?J8(this,a):b&&this.Sa.seekTo(a)};
g.h.SC=function(){if(H8(this)){var a=Z7(this.Sa);this.events.fb(this.J);a.muted?this.K.mute():this.K.unMute();this.K.setVolume(a.volume);this.J=this.events.M(this.K,"onVolumeChange",this.JA)}};
g.h.pC=function(){this.o.stop();if(!this.Sa.ha()){var a=Z7(this.Sa);a.gb()&&G8(this,new g.FC(8));this.Sb(U7(a));this.o.start()}};
g.h.qC=function(){this.u.stop();this.o.stop();var a=this.Sa.B.getReconnectTimeout();2==this.Sa.o&&!isNaN(a)&&this.u.start()};g.r(K8,g.Q);K8.prototype.Ub=function(){this.u.show()};
K8.prototype.A=function(){g.PN("https://support.google.com/youtube/answer/7640706")};
K8.prototype.B=function(){c6("mdx-manual-pairing-popup-ok");this.u.hide()};g.r(L8,g.Q);L8.prototype.Ub=function(){this.u.show()};
L8.prototype.A=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
L8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(M8,g.Q);M8.prototype.A=function(a){xza(this,a.state)};g.r(N8,g.pP);N8.prototype.D=function(){var a=this.K.getOption("remote","receivers");a&&1<a.length&&!this.K.getOption("remote","quickCast")?(this.Uh=g.xb(a,this.A,this),g.rP(this,(0,g.Hc)(a,this.A)),a=this.K.getOption("remote","currentReceiver"),this.Db(this.A(a)),this.enable(!0)):this.enable(!1)};
N8.prototype.A=function(a){return a.key};
N8.prototype.df=function(a){return"cast-selector-receiver"===a?"Cast...":this.Uh[a].name};
N8.prototype.kd=function(a){g.pP.prototype.kd.call(this,a);this.K.setOption("remote","currentReceiver",this.Uh[a]);this.u.kb()};g.r(O8,g.ML);g.h=O8.prototype;
g.h.create=function(){oza(g.Oy(this.player.O()));this.subscriptions.push(g.To("yt-remote-before-disconnect",this.vK,this));this.subscriptions.push(g.To("yt-remote-connection-change",this.FM,this));this.subscriptions.push(g.To("yt-remote-receiver-availability-change",this.bB,this));this.subscriptions.push(g.To("yt-remote-auto-connect",this.DM,this));this.subscriptions.push(g.To("yt-remote-receiver-resumed",this.CM,this));this.subscriptions.push(g.To("mdx-privacy-popup-confirm",this.UN,this));this.subscriptions.push(g.To("mdx-privacy-popup-cancel",
this.TN,this));this.subscriptions.push(g.To("mdx-manual-pairing-popup-ok",this.wG,this));this.bB()};
g.h.load=function(){this.player.cancelPlayback();g.ML.prototype.load.call(this);this.ae=new F8(this,this.player,this.Sa);var a=(a=tza())?a.currentTime:0;var b=B8()?new Y7(w8(),void 0):null;0==a&&b&&(a=U7(Z7(b)));0!==a&&this.Sb(a);wza(this,this.Jb,this.Jb);g.jT(this.player.app,6)};
g.h.unload=function(){this.player.T("mdxautoplaycanceled");this.fh=this.bf;g.Me(this.ae,this.Sa);this.Sa=this.ae=null;g.ML.prototype.unload.call(this);g.jT(this.player.app,5);P8(this)};
g.h.Y=function(){g.Uo(this.subscriptions);g.ML.prototype.Y.call(this)};
g.h.Mf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.ae.oz.apply(this.ae,[a].concat(g.la(c)))};
g.h.getAdState=function(){return this.Tc};
g.h.lF=function(){return this.loaded?this.ae.suggestion:null};
g.h.Af=function(){return this.Sa?Z7(this.Sa).Af:!1};
g.h.hasNext=function(){return this.Sa?Z7(this.Sa).hasNext:!1};
g.h.Sb=function(a,b){this.Cy=a||0;this.player.T("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.Cy};
g.h.getProgressState=function(){var a=Z7(this.Sa),b=this.player.getVideoData();return{allowSeeking:g.O(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Sc():!a.isAdPlaying()&&this.player.Sc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+S7(a):a.B,isAtLiveHead:1>=(a.A?a.u+S7(a):a.u)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.A?a.u+S7(a):a.u,seekableStart:0<a.C?a.C+
S7(a):a.C}};
g.h.nextVideo=function(){this.Sa&&this.Sa.nextVideo()};
g.h.Np=function(){this.Sa&&this.Sa.Np()};
g.h.vK=function(a){1===a&&(this.lu=this.Sa?Z7(this.Sa):null)};
g.h.FM=function(){var a=B8()?new Y7(w8(),void 0):null;if(a){var b=this.fh;this.loaded&&this.unload();this.Sa=a;this.lu=null;b.key!==this.bf.key&&(this.fh=b,this.load())}else g.Le(this.Sa),this.Sa=null,this.loaded&&(this.unload(),(a=this.lu)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,U7(a)));this.player.T("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.bB=function(){this.Uh=[this.bf].concat(qza());var a=x8()||this.bf;Q8(this,a);this.player.sa("onMdxReceiversChange")};
g.h.DM=function(){var a=x8();Q8(this,a)};
g.h.CM=function(){this.fh=x8()};
g.h.UN=function(){this.zm=!0;P8(this);D8=!1;E8&&z8(E8,1);E8=null};
g.h.TN=function(){this.zm=!1;P8(this);Q8(this,this.bf);this.fh=this.bf;D8=!1;E8=null;this.player.playVideo()};
g.h.wG=function(){this.Po=!0;P8(this);g.ws("yt-remote-manual-pairing-warning-shown",!0,2592E3);D8=!1;E8&&z8(E8,1);E8=null};
g.h.Qc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Uh;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?O7():Q8(this,b)),this.loaded?this.fh:this.bf;case "quickCast":return 2===this.Uh.length&&"cast-selector-receiver"===this.Uh[1].key?(b&&O7(),!0):!1}};
g.h.Xu=function(){this.Sa.Xu()};
g.h.jf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.aM.remote=O8;})(_yt_player);
